### ISSUE TITLE
Add button to center image and center canvas

### ISSUE THREAD

**Issue by azagaya** [MeanLight-Studio/ScaleNX#1]
If we add multiple image support, we should be able to center each of them sepparately. There should be a way to center canvas in the origin, and another way to bring the image to the center.

**Comment by webocs** [comment]
Center to origin sounds fine to me, if we support multiple images there's also "Zoom to fit" where we determine the correct zoom value to show all the images on a single screen, but that's a different feature IMO.

**Comment by azagaya** [comment]
Implemented zoom to fit. It was implemented but wasnt working correctly.
