### ISSUE TITLE
Proposal: Moving the scale control

### ISSUE THREAD

**Issue by webocs** [MeanLight-Studio/ScaleNX#10]
One option we have for moving the scale control that is now floating in the top right without much meaning could be to do something like this:

![image](https://user-images.githubusercontent.com/2563911/139555500-5da86ae3-af85-4ca7-bce2-4b9e9e13d162.png)

This will be useful when supporting multiple images, especially if we are allowing independent scales for each uploaded image. The control must have the same outline color as the outline for the selected texture, making it look like a tab. 

### Challenges
- The size of the panel when the image is too zoomed out
- Finding available space for the panel if the border of the image is aligned with the bottom of the screen
-  What happens with the "Scale multiple images feature"?

**Comment by azagaya** [comment]
Implemented something similar in master branch. Is it ok like that?

**Comment by webocs** [comment]
I like it! We should prepare a release for itch, I can write the changelog
