### ISSUE TITLE
Multiple Images at the same time

### ISSUE THREAD

**Issue by azagaya** [MeanLight-Studio/ScaleNX#6]
Will need to rework the way things are moved (now i just panned the camera).

To discuss with @webocs :

* Clicking on an image should select that image to show the metadata and be able to scale it.
* Perhaps a list of all the opened images would be useful.
* Ctrl + Click to multiple select, so you can scale those images together.

**Comment by webocs** [comment]
For the time being, there are 4 tools that we have for the user to interact with the software

- Select
- move 
- Pan
- Zoom

Maybe we can add rostrprite in the future and add a rotate tool.  In this context, maybe we can benefit of having UI buttons on the top left part of the screen to alternate between them as most editors do

**Comment by webocs** [comment]
Agreed with ctrl+click for multiple selection

**Comment by azagaya** [comment]
I think is enough with what was implemented for now.
