### ISSUE TITLE
Some missing features and UI stuff

### ISSUE THREAD

**Issue by webocs** [MeanLight-Studio/ScaleNX#9]
Some basic features and UI stuff that we're still missing and are required:

### Features (For when we have multiple textures):
- When importing multiple textures, there's no way to remove them from the canvas. We need to add SUPR to remove with a warning popup and maybe add it to a right-click menu?
- We need a feature in the File menu to clear the entire canvas, removing all textures. Something like New project

### UI
- Rename "Reset pan" to "Center in origin"
- Maybe add a dot at the origin, to realize that's 0,0 
- Selected texture outline needs to be a few px wider
- In the open file menu:
    -  Remember the last opened directory
    -  Maybe have a recently accessed section

**Comment by azagaya** [comment]
- [x] Remove with Delete
- [x] Ad warning popup when deleting
- [x] Clear canvas file menu entry
- [x] Reset Pan to Center in origin
- [x] Origin indicator
- [ ] Wider outline
- [ ] Remember last opened directory
- [ ] Recently opened

**Comment by azagaya** [comment]
I found a bug in the ReferenceRect node in godot, so making the outline wider would need a workarround.
I would prefere to leave the reference rect 1px wide and wait for a fix, or submit a fix to the engine.

**Comment by azagaya** [comment]
@webocs desktop version already remembers last opened directory. Should i implement it also for web, or let it just as a desktop feature?

**Comment by azagaya** [comment]
I won't implement recently opened section for now i think, because it would require to save on disk, and on html wont work. We may add it if someone requests it.

**Comment by azagaya** [comment]
Im closing this for now, the tasks missing dont worth the trouble imho.
